/** @type {import('@types/eslint').Linter.BaseConfig} */

module.exports = {
  extends: ["prettier"],
  parserOptions: {
    sourceType: "module",
  },
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  rules: {
    settings: {
      "import/extensions": [".js", ".jsx"],
    },
    "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
    "import/default": "error",
    "import/dynamic-import-chunkname": "error",
    "import/export": "error",
    "import/exports-last": "error",
    "import/extensions": ["error", "always", { ignorePackages: true }],
    "import/first": "error",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/named": "error", // turn off for TS
    "import/namespace": "error",
    "import/newline-after-import": "warn",
    "import/no-absolute-path": "error",
    "import/no-amd": "error",
    "import/no-anonymous-default-export": "off",
    "import/no-commonjs": "off",
    "import/no-cycle": "error",
    "import/no-default-export": "off",
    "import/no-deprecated": "warn",
    "import/no-duplicates": "error",
    "import/no-dynamic-require": "error",
    "import/no-empty-named-blocks": "warn",
    "import/no-extraneous-dependencies": "error",
    "import/no-import-module-exports": "off",
    "import/no-internal-modules": "off",
    "import/no-mutable-exports": "error",
    "import/no-named-as-default-member": "error",
    "import/no-named-as-default": "error",
    "import/no-named-default": "error",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-restricted-paths": "off",
    "import/no-self-import": "error",
    "import/no-unassigned-import": "error",
    "import/no-unresolved": "error",
    "import/no-unused-modules": "off",
    "import/no-useless-path-segments": "warn",
    "import/no-webpack-loader-syntax": "error",
    "import/order": "off",
    "import/prefer-default-export": "off",
    "import/unambiguous": "off",
  },
  overrides: [
    {
      files: ["**/*.ts?(x)"],
      extends: "plugin:import/typescript",
      parser: "@typescript-eslint/parser",
      parserOptions: {
        sourceType: "module",
      },
      plugins: ["@typescript-eslint"],
      rules: {
        "import/no-unresolved": "off",
      },
    },
  ],
}
